# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 14:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RootAC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('rootac_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artcasting.RootAC')),
                ('destination', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('origin', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('explanation', models.TextField(blank=True)),
                ('speed', models.IntegerField(blank=True)),
                ('has_arrived', models.NullBooleanField(default=None)),
                ('is_a_recast', models.NullBooleanField(default=None)),
                ('needs_review', models.NullBooleanField(default=None)),
                ('arrival', models.DateTimeField(blank=True)),
            ],
            bases=('artcasting.rootac',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rootac_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artcasting.RootAC')),
                ('postcode', models.CharField(blank=True, max_length=250)),
                ('postcode_geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('platform', models.CharField(blank=True, choices=[('I', 'iOS'), ('A', 'Android'), ('W', 'Web')], max_length=1)),
            ],
            bases=('artcasting.rootac',),
        ),
    ]
