# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcasting', '0002_auto_20160113_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('A', '12 or under'), ('B', '13-15'), ('C', '16-17'), ('D', '18-20'), ('E', '21-23'), ('F', '24-26'), ('G', '27-35'), ('H', '36-45'), ('I', '46-55'), ('J', '56-74'), ('K', '75 or older'), ('N', 'No Answer')], default='N', max_length=1),
        ),
    ]
