# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcasting', '0004_user_encounters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('rootac_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artcasting.RootAC')),
                ('asset_name', models.CharField(max_length=250, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=250)),
                ('artist_name', models.CharField(blank=True, max_length=250)),
                ('year_produced', models.IntegerField(default=0)),
            ],
            bases=('artcasting.rootac',),
        ),
    ]
