# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcasting', '0007_cast_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='artwork_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cast',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='here_before',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cast',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='recast_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='user_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
