# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 10:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcasting', '0008_auto_20160406_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
